// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUnit(arg1, arg2) {
  return window['go']['main']['App']['GetUnit'](arg1, arg2);
}

export function ListAllUnits() {
  return window['go']['main']['App']['ListAllUnits']();
}

export function Open() {
  return window['go']['main']['App']['Open']();
}

export function Save() {
  return window['go']['main']['App']['Save']();
}
