// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteUnit(arg1:string,arg2:number):Promise<void>;

export function GetUnit(arg1:string,arg2:number):Promise<main.Unit>;

export function ListAllUnits():Promise<Array<main.Unit>>;

export function ListAvailableProperties(arg1:string):Promise<Array<main.Property>>;

export function NextUnitID(arg1:string):Promise<number>;

export function Open():Promise<void>;

export function Save():Promise<void>;

export function SaveUnit(arg1:main.Unit):Promise<void>;

export function UserRules():Promise<string>;
