// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteUnit(arg1, arg2) {
  return window['go']['main']['App']['DeleteUnit'](arg1, arg2);
}

export function GetUnit(arg1, arg2) {
  return window['go']['main']['App']['GetUnit'](arg1, arg2);
}

export function ListAllUnits() {
  return window['go']['main']['App']['ListAllUnits']();
}

export function ListAvailableProperties(arg1) {
  return window['go']['main']['App']['ListAvailableProperties'](arg1);
}

export function NextUnitID(arg1) {
  return window['go']['main']['App']['NextUnitID'](arg1);
}

export function Open() {
  return window['go']['main']['App']['Open']();
}

export function Save() {
  return window['go']['main']['App']['Save']();
}

export function SaveUnit(arg1) {
  return window['go']['main']['App']['SaveUnit'](arg1);
}

export function UserRules() {
  return window['go']['main']['App']['UserRules']();
}
