// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetUnit(arg1:string,arg2:number):Promise<main.Unit>;

export function ListAllUnits():Promise<Array<main.Unit>>;

export function Open():Promise<void>;

export function Save():Promise<void>;
